[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
process-max=2
start-fast=y
log-level-console=info

[akasha]
pg1-path=/var/lib/postgresql/data
pg1-socket-path=/var/run/postgresql
pg1-user=akasha
